# Generated by Django 4.2.3 on 2023-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Django', '0005_alter_advertisements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default=1, upload_to='Django/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
